/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    maven("https://repo.papermc.io/repository/maven-public/")
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    compileOnly("com.github.hyperdefined:hyperlib:1.0.14:all")
}

group = "lol.hyper"
version = "1.4.3"
description = "NoEndCrystals"
java.sourceCompatibility = JavaVersion.VERSION_24

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

val pluginVersion = version.toString()

tasks.processResources {
    filteringCharset = "UTF-8"

    val props = mapOf("version" to pluginVersion)
    inputs.properties(props)

    filesMatching("paper-plugin.yml") {
        expand(props)
    }
}