# Toggle white/black list for limiting End Crystals.
# True: End Crystals are allowed in these worlds only.
# False: End Crystals are not allowed in these worlds.
whitelist: true
worlds:
  - world
  - world_nether
  - world_the_end
message: '<red>End Crystals are disabled in this world.'

config-version: 1