# Toggle white/black list for limiting End Crystals.
# True: End Crystals are allowed in these worlds only.
# False: End Crystals are not allowed in these worlds.
whitelist: true
worlds:
  - world1
  - world2
  - world3
message: '<red>End Crystals are disabled in this world.</red>'

config-version: 1