name: NoEndCrystals
version: ${project.version}
main: lol.hyper.noendcrystals.NoEndCrystals
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/noendcrystals.77559/
description: Disable/enable placement of End Crystals in certain worlds.
commands:
  noendcrystals:
    usage: /noendcrystals
permissions:
  noendcrystals.reload:
    description: Reload configuration.
    default: op