name: NoEndCrystals
main: lol.hyper.noendcrystals.NoEndCrystals
authors: [ hyperdefined ]
version: ${project.version}
api-version: 1.15
commands:
  noendcrystals:
    usage: /noendcrystals
    description: Main command.
permissions:
  noendcrystals.reload:
    description: Reload configuration.
    default: op